# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Campus-Plus' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Campus-Plus

  pod 'AFNetworking'
  pod 'BlocksKit'
  pod 'ChameleonFramework'
  pod 'Fabric'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'Realm'
  pod 'SDWebImage'
  pod 'SCLAlertView-Objective-C'
  pod 'UMengAnalytics'
  pod 'YYModel'

  target 'Campus-PlusTests' do
    # inherit! :search_paths
    # Pods for testing
  end

  target 'Campus-PlusUITests' do
    # inherit! :search_paths
    # Pods for testing
  end

end
